name: Build

on:
  push:
    branches:
      - 'develop'
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Setup pnpm'
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: 'Install packages'
        run: 'pnpm install'

      - name: 'Lint'
        run: 'pnpm lint'

      - name: 'Build'
        run: 'pnpm build:stage'

      - name: 'Stage'
        id: 'stage'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PERSONAL_SITE }}
          channelId: ${{ github.ref_name }}

      - name: 'Setup Playwright'
        run: 'pnpm exec playwright install'

      - name: 'E2E'
        run: 'BASE_URL=${{ steps.stage.outputs.details_url }} pnpm e2e'
