name: Deploy

on:
  push:
    branches:
      - 'release'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: 'Install packages'
        run: 'npm ci'

      - name: 'Build'
        run: 'npm run build'

      - name: 'Export'
        run: 'npm run export'

      - name: 'Deploy'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PERSONAL_SITE }}
          channelId: live
